# FsgDvDrivingDynamics1
# Frame id:   0x500
# Senders:    VCU_Driverless,DVPC
# Cycle time: -

builtin_interfaces/Time stamp

# Range: -
# Unit:  km/h
float32 speed_actual

# Range: -
# Unit:  km/h
float32 speed_target

# Range: -
# Unit:  °
float32 steering_angle_actual

# Range: -
# Unit:  °
float32 steering_angle_target

# Range: -
# Unit:  %
float32 brake_hydr_actual

# Range: -
# Unit:  %
float32 brake_hydr_target

# Range: -
# Unit:  %
float32 motor_moment_actual

# Range: -
# Unit:  %
float32 motor_moment_target
