# KistlerStatus
# Frame id:   0x7e8
# Senders:    SMotion
# Cycle time: -

builtin_interfaces/Time stamp

# Range: 0..9999 
# Unit:  -
float32 sensor_id

# Range: -128..127 °C
# Unit:  °C
float32 temperature

# Range: 0..2.55 A
# Unit:  A
float32 lamp_current

# Range: 0..255 
# Unit:  -
float32 filter_setting

# Range: 0..1 
# Unit:  -
float32 direction

# Range: 0..1 
# Unit:  -
float32 angle_switched_off

# Range: 0..3 
# Unit:  -
float32 head_status

# Range: 0..1 
# Unit:  -
float32 temperature_ok

# Range: 0..1 
# Unit:  -
float32 lamp_current_control

# Range: 0..1 
# Unit:  -
float32 filter_off_on

# Range: 0..1 
# Unit:  -
float32 stst

# Range: 0..1 
# Unit:  -
float32 direction_head

# Range: 0..1 
# Unit:  -
float32 direction_head_is_valid

# Range: 0..1 
# Unit:  -
float32 direction_mounting

# Range: 0..1 
# Unit:  -
float32 direction_motion

# Range: 0..1 
# Unit:  -
float32 ang_vel_correction
