# https://github.com/cantools/cantools/blob/master/src/cantools/database/can/c_source.py

import textwrap
import time
from typing import (
    TYPE_CHECKING,
    List,
    Tuple,
)

from cantools import __version__
from util import CodeGenMessage, CodeGenSignal

if TYPE_CHECKING:
    from cantools.database.can import Database

THelperKind = Tuple[str, int]

from os import environ

season = environ.get("SEASON")
if season is None:
    raise Exception("Environment variable 'SEASON' needs to be set (for example 16)")

SOURCE_FMT = """\
/**
 * This file was generated by a vcu_can_generator {version}.
 */

#include <string.h>

#include "generated/{header}"

{includes}\

void {raw_database_name}Data::receive(struct can_frame *frame, int bytes_read)
{{

    {definitions}\

}}


void {database_name}DataInitializePublishers({raw_database_name}Data* reader, rclcpp::Node::SharedPtr node)
{{
{publisher_init}\
}}

{to_message_members}
"""

"""
// auto src_p = &{database_name}_{message_name};
/*
{decode_body}\
*/
"""
MESSAGE_DEFINITION_DECODE_FMT = """\
if (frame->can_id == {frame_id}) {{
        // Decode {database_name} frame id {frame_id} message {raw_message_name}
        if ({database_name}_{message_name}_t::unpack(
            &this->{database_name}_{message_name},
            frame->data, bytes_read) != 0) {{
            // Handle error
        }}

        auto msg = this->{database_name}_{message_name}.to_msg();

        msg.stamp = this->node->now();

        {database_name}_{message_name}_pub->publish(msg);
    }}\
"""

MESSAGE_DEFINITION_TO_MSG_FMT = """\
vcu_can_msgs_yourcar{season}::msg::{ros_message_name} {database_name}_{message_name}_t::to_msg() {{
    auto src_p = this;
    auto msg = vcu_can_msgs_yourcar{season}::msg::{ros_message_name}();

    // msg.stamp = this->node->now();

{decode_body}\

    return msg;
}}\
"""

MESSAGE_DEFINITION_TO_CAN_FMT = """\
size_t send_on_can(int fd, const vcu_can_msgs_yourcar{season}::msg::{ros_message_name}& msg) {{
    struct can_frame msg_frame;
    msg_frame.can_id = {frame_id};
    msg_frame.len = {size};

    struct {database_name}_{hex_snake_name}_t tmp;
    {database_name}_{hex_snake_name}_t::from_msg(&tmp, msg);
    tmp.pack(msg_frame.data, {size});

    return write(fd, &msg_frame, sizeof(struct can_frame));
}}\
"""

MESSAGE_DEFINITION_FROM_MSG_FMT = """\
void {database_name}_{message_name}_t::from_msg(
    struct {database_name}_{message_name}_t *dst_p,
    const vcu_can_msgs_yourcar{season}::msg::{ros_message_name} &src_p) {{

{encode_body}\

}}\
"""


def _generate_encode_decode(
    cg_signal: "CodeGenSignal", use_float: bool
) -> Tuple[str, str]:
    floating_point_type = cg_signal.cpp_ros_type_name

    scale = cg_signal.signal.scale
    offset = cg_signal.signal.offset

    scale_literal = (
        f"{scale}{'.0' if isinstance(scale, int) else ''}{'f' if use_float else ''}"
    )
    offset_literal = (
        f"{offset}{'.0' if isinstance(offset, int) else ''}{'f' if use_float else ''}"
    )

    if offset == 0 and scale == 1:
        encoding = "value"
        # Do not cast values with choices
        if cg_signal.signal.choices:
            decoding = f"value"
        else:
            decoding = f"({floating_point_type})value"
    elif offset != 0 and scale != 1:
        encoding = f"(value - {offset_literal}) / {scale_literal}"
        decoding = (
            f"(({floating_point_type})value * {scale_literal}) + {offset_literal}"
        )
    elif offset != 0:
        encoding = f"value - {offset_literal}"
        decoding = f"({floating_point_type})value + {offset_literal}"
    else:
        encoding = f"value / {scale_literal}"
        decoding = f"({floating_point_type})value * {scale_literal}"

    return encoding, decoding


def _generate_full_decode(
    database_name: str, cg_message: CodeGenMessage, use_float: bool
) -> str:
    """
    Decode the whole struct with all it's values to transfer it into ROS messages
    """

    decode_body = ""
    for cg_signal in cg_message.cg_signals:
        _, decode = _generate_encode_decode(cg_signal, use_float)
        decode_body += "    msg." + cg_signal.snake_name + " = "
        decode_body += (
            decode.replace("value", f"(src_p->{cg_signal.snake_name})") + ";\n\t"
        )

    if decode_body == "":
        decode_body = "    (void)src_p;\n"

    ros_message_name = database_name + cg_message.pascal_name

    return MESSAGE_DEFINITION_DECODE_FMT.format(
        database_message_name=cg_message.message.name,
        message_name=cg_message.hex_snake_name,
        raw_message_name=cg_message.message.name,
        ros_message_name=ros_message_name,
        database_name=database_name.lower(),
        frame_id=hex(cg_message.message.frame_id),
        decode_body=decode_body,
    )


def _generate_to_msg(
    database_name: str, cg_message: CodeGenMessage, use_float: bool
) -> str:
    """
    Decode the whole struct with all it's values to transfer it into ROS messages
    """

    decode_body = ""
    for cg_signal in cg_message.cg_signals:
        _, decode = _generate_encode_decode(cg_signal, use_float)
        decode_body += "msg." + cg_signal.snake_name + " = "
        decode_body += (
            decode.replace("value", f"(src_p->{cg_signal.snake_name})") + ";\n"
        )

    if decode_body == "":
        decode_body = "    (void)src_p;\n"

    decode_body = textwrap.indent(decode_body, " " * 4)

    ros_message_name = database_name + cg_message.pascal_name

    return MESSAGE_DEFINITION_TO_MSG_FMT.format(
        database_message_name=cg_message.message.name,
        message_name=cg_message.hex_snake_name,
        raw_message_name=cg_message.message.name,
        ros_message_name=ros_message_name,
        database_name=database_name.lower(),
        frame_id=hex(cg_message.message.frame_id),
        decode_body=decode_body,
        season=season,
    )


def _generate_msg_send_to_can(
    database_name: str, cg_message: CodeGenMessage, use_float: bool
) -> str:
    """ """
    ros_message_name = database_name + cg_message.pascal_name

    return MESSAGE_DEFINITION_TO_CAN_FMT.format(
        ros_message_name=ros_message_name,
        hex_snake_name=cg_message.hex_snake_name,
        database_name=database_name.lower(),
        size=cg_message.message.length,
        frame_id=hex(cg_message.message.frame_id),
        season=season,
    )


def _generate_from_msg(
    database_name: str, cg_message: CodeGenMessage, use_float: bool
) -> str:
    """
    Decode the whole struct with all it's values to transfer it into ROS messages
    """

    encode_body = ""
    for cg_signal in cg_message.cg_signals:
        encode, _ = _generate_encode_decode(cg_signal, use_float)
        encode_body += "dst_p->" + cg_signal.snake_name + f" = ({cg_signal.type_name})("
        encode_body += (
            encode.replace("value", f"(src_p.{cg_signal.snake_name})") + ");\n"
        )

    if encode_body == "":
        encode_body = textwrap.indent("(void)src_p;\n(void)dst_p;\n", " " * 4)

    encode_body = textwrap.indent(encode_body, " " * 4)

    ros_message_name = database_name + cg_message.pascal_name

    return MESSAGE_DEFINITION_FROM_MSG_FMT.format(
        database_message_name=cg_message.message.name,
        message_name=cg_message.hex_snake_name,
        raw_message_name=cg_message.message.name,
        ros_message_name=ros_message_name,
        database_name=database_name.lower(),
        frame_id=hex(cg_message.message.frame_id),
        encode_body=encode_body,
        season=season,
    )


def _get_floating_point_type(use_float: bool) -> str:
    return "float" if use_float else "double"


def _generate_definitions(
    database_name: str, cg_messages: List["CodeGenMessage"]
) -> tuple[str, str]:
    definitions = []
    to_message_members = []

    for cg_message in cg_messages:
        definition = _generate_full_decode(database_name, cg_message, False)
        definitions.append(definition)
        to_message_members.append(_generate_to_msg(database_name, cg_message, False))
        to_message_members.append(
            _generate_msg_send_to_can(database_name, cg_message, False)
        )
        to_message_members.append(_generate_from_msg(database_name, cg_message, False))

    return " else ".join(definitions), "\n\n".join(to_message_members)


def gen_c_decoding(
    database: "Database", database_name: str, header_name: str, commit_hash: str
) -> str:
    """Generate C source code from given CAN database `database`.

    `database_name` is used as a prefix for all defines, data
    structures and functions.

    `header_name` is the file name of the C header file, which is
    included by the C source file.

    This function returns a CPP file containing the code for decoding the unpacked messages
    """

    # date = time.ctime()
    date = commit_hash
    cg_messages = [CodeGenMessage(message) for message in database.messages]

    definitions, to_message_members = _generate_definitions(database_name, cg_messages)

    includes = ""
    for msg in cg_messages:
        includes += f'#include "vcu_can_msgs_yourcar{season}/msg/{database_name.lower()}_{msg.snake_name}.hpp"\n'

    publisher_init = ""
    for msg in cg_messages:
        publisher_init += f'   reader->{database_name.lower()}_{msg.hex_snake_name}_pub = node->create_publisher<vcu_can_msgs_yourcar{season}::msg::{database_name}{msg.pascal_name}>("/sensor/{database_name.lower()}/{msg.snake_name}", 3);\n'

    source = SOURCE_FMT.format(
        version=__version__,
        date=commit_hash,
        raw_database_name=database_name,
        database_name=database_name.lower(),
        header=header_name,
        includes=includes,
        definitions=definitions,
        publisher_init=publisher_init,
        to_message_members=to_message_members,
    )

    return source
