from os import environ
from typing import (
    TYPE_CHECKING,
    List,
    Optional,
    Tuple,
    Union,
)

from cantools.database.can import Database, Message
from util import CodeGenMessage, CodeGenSignal, _get

THelperKind = Tuple[str, int]

season = environ.get("SEASON")
if season is None:
    raise Exception("Environment variable 'SEASON' needs to be set (for example 16)")

MESSAGE_FMT = """\
# {message_name}
# Frame id:   {frame_id}
# Senders:    {senders}
# Cycle time: {cycle_time}
{comment}\

builtin_interfaces/Time stamp

{members}
"""

# Maybe add
# Scale: {scale} | Offset: {offset}
SIGNAL_MEMBER_FMT = """\
# Range: {range}
# Unit:  {unit}
{comment}\
{type_name} {name}{length}\
"""

PACKAGE_XML_FMT = """\
<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vcu_can_msgs_yourcar{season}</name>
  <version>1.0.0</version>
  <description>ROS Messages for the CAN messages</description>
  <maintainer email="marvin.jacob@elbflorace.de">Marvin</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <build_depend>rosidl_default_generators</build_depend>
  <build_depend>message_runtime</build_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>builtin_interfaces</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>visualization_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
"""

CMAKE_FMT = """\
cmake_minimum_required(VERSION 3.8)
project(vcu_can_msgs_yourcar{season})

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic -Werror)
endif()

# find dependencies
find_package(ament_cmake REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(visualization_msgs REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(std_msgs REQUIRED)
find_package(rosidl_default_generators REQUIRED)
find_package(builtin_interfaces REQUIRED)

file(GLOB ROS_MSG_FILES RELATIVE ${{PROJECT_SOURCE_DIR}} msg/*.msg)

rosidl_generate_interfaces(
   ${{PROJECT_NAME}}

   ${{ROS_MSG_FILES}}

   DEPENDENCIES
   geometry_msgs
   visualization_msgs
   std_msgs
   sensor_msgs
)
ament_export_dependencies(std_msgs geometry_msgs rosidl_default_runtime visualization_msgs)
ament_export_include_directories(
  include
)

ament_package()
"""

README_FMT = """\
## Contact Person(s)
Marvin Jacob, marvin.jacob@elbflorace.de

## Intention
This package is fully generated by the [`vcu_can_generator`](../vcu_can_generator/) package and contains all the available CAN Messages as ROS messages.
For the most part these messages only get published by the mailman ( under the topic `/sensor/{{canName}}/{{messageName}}`, for example `/sensor/can1/pressure_sus` ) and used by the monitoring backend.

The messages in this package are not guaranteed to stay the same forever so use them with caution.
All files were generated at commit `{commit_hash}`


## Usage
### Examples
```cpp
#include "vcu_can_msgs_yourcar{season}/msg/can4_gps_rear_velocities.hpp"

auto msg = vcu_can_msgs_yourcar{season}::msg::Can4GpsRearVelocities();
```

## Resources
 - https://git.elbflorace.de/control/efr16ed04/can-dbc-efr16
 - The `vcu_can_generator` package
"""


def _format_comment(comment: Optional[str]) -> str:
    if comment:
        return (
            "\n".join(["# " + line.rstrip() for line in comment.splitlines()]) + "\n#\n"
        )
    else:
        return ""


def _format_signal_comment(cg_signal: CodeGenSignal) -> str:

    comment = cg_signal.signal.comment
    result = ""
    if comment:
        result += (
            "\n".join(["# " + line.rstrip() for line in comment.splitlines()]) + "\n#\n"
        )

    if cg_signal.signal.choices:
        result += "# Choices:\n"
        for k, v in cg_signal.signal.choices.items():
            result += f"# {k} = {v}\n"

    return result


def _format_range(cg_signal: "CodeGenSignal") -> str:
    minimum = cg_signal.signal.minimum
    maximum = cg_signal.signal.maximum

    def phys_to_raw(x: Union[int, float]) -> Union[int, float]:
        raw_val = cg_signal.signal.scaled_to_raw(x)
        if cg_signal.signal.is_float:
            return float(raw_val)
        return round(raw_val)

    unit = cg_signal.unit
    if unit == "-":
        unit = ""

    if minimum is not None and maximum is not None:
        return f"{round(minimum, 5)}..{round(maximum, 5)} {unit}"
    elif minimum is not None:
        return f"{phys_to_raw(minimum)}.. ({round(minimum, 5)}.. {unit})"
    elif maximum is not None:
        return f"..{phys_to_raw(maximum)} (..{round(maximum, 5)} {unit})"
    else:
        return "-"


def _generate_signal(cg_signal: "CodeGenSignal", bit_fields: bool) -> str:
    comment = _format_signal_comment(cg_signal)
    range_ = _format_range(cg_signal)
    scale = _get(cg_signal.signal.conversion.scale, "-")
    offset = _get(cg_signal.signal.conversion.offset, "-")

    if cg_signal.signal.conversion.is_float or not bit_fields:
        length = ""
    else:
        length = f" : {cg_signal.signal.length}"

    member = SIGNAL_MEMBER_FMT.format(
        comment=comment,
        range=range_,
        scale=scale,
        offset=offset,
        type_name=cg_signal.ros_type_name,
        name=cg_signal.snake_name,
        length=length,
        unit=cg_signal.unit,
    )

    return member


def generate_ros_message(
    database_name: str, message: Message, commit_hash: str
) -> Tuple[str, str]:
    """
    Filename, File content
    """
    cg_message = CodeGenMessage(message)
    members = []

    for cg_signal in cg_message.cg_signals:
        members.append(_generate_signal(cg_signal, False))

    if not members:
        members = [""]

    comment = _format_comment(cg_message.message.comment)

    message_name = database_name + cg_message.pascal_name

    if cg_message.message.cycle_time is None:
        cycle_time = "-"
    else:
        cycle_time = str(cg_message.message.cycle_time) + " ms"

    message_definition = MESSAGE_FMT.format(
        comment=comment,
        message_name=message_name,
        commit_hash=commit_hash,
        frame_id=hex(cg_message.message.frame_id),
        cycle_time=cycle_time,
        senders=",".join(cg_message.message.senders),
        members="\n\n".join(members),
    )

    file_name = f"{message_name}.msg"

    return file_name, message_definition


def generate_ros_package_xml() -> str:
    xml_content = PACKAGE_XML_FMT.format(season=season)

    return xml_content


def generate_ros_cmake_list(
    dbs: List[Tuple[str, Database]], ros_addons: List[str]
) -> str:
    import os.path

    # Add the addon ROS message files
    message_list = ""
    for ros_addon in ros_addons:
        filename = os.path.basename(ros_addon)
        message_list += f'  "msg/{filename}"\n'
    message_list += "\n"

    # Add the CAN ROS message files
    for database_name, db in dbs:
        cg_messages = [CodeGenMessage(message) for message in db.messages]

        for msg in cg_messages:
            name = msg.pascal_name
            message_list += f'  "msg/{database_name}{name}.msg"\n'
        message_list += "\n"

    cmake_list = CMAKE_FMT.format(message_list=message_list, season=season)
    return cmake_list


def generate_ros_readme(commit_hash: str) -> str:
    readme_content = README_FMT.format(commit_hash=commit_hash, season=season)

    return readme_content
