# https://github.com/cantools/cantools/blob/master/src/cantools/database/can/c_source.py

import time
import warnings
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
    Set,
    Tuple,
    TypeVar,
    Union,
)

from util import CodeGenMessage, CodeGenSignal, __version__

if TYPE_CHECKING:
    from cantools.database.can import Database

_T1 = TypeVar("_T1")
_T2 = TypeVar("_T2")
THelperKind = Tuple[str, int]

from os import environ

season = environ.get("SEASON")
if season is None:
    raise Exception("Environment variable 'SEASON' needs to be set (for example 16)")

HEADER_FMT_DEFINES = """\
/* Frame ids. */
{frame_id_defines}

/* Frame lengths in bytes. */
{frame_length_defines}

/* Extended or standard frame types. */
{is_extended_frame_defines}

/* Frame cycle times in milliseconds. */
{frame_cycle_time_defines}

/* Signal choices. */
{choices_defines}

/* Frame Names. */
{frame_name_macros}

/* Signal Names. */
{signal_name_macros}

"""

HEADER_FMT = """\
/**
 * This file was generated by the vcu_can_generator version {version}.
 */

#ifndef {include_guard}
#define {include_guard}

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <linux/can.h>
#include "rclcpp/rclcpp.hpp"

{includes}\

#ifndef EINVAL
#    define EINVAL 22
#endif

{structs}


class {raw_database_name}Data
{{
public:
    {raw_database_name}Data(
        rclcpp::Node::SharedPtr node
    ) :
        node(node)
    {{
    }}

    rclcpp::Node::SharedPtr node;

{variable_declarations}

{function_declarations}
    void receive(struct can_frame *frame, int bytes_read);

private:
}};

void {lower_database_name}DataInitializePublishers({raw_database_name}Data* reader, rclcpp::Node::SharedPtr node);

#endif
"""

SOURCE_FMT = """\
/**
 * This file was generated by the vcu_can_generator {version}.
 */

#include <string.h>

#include "generated/{header}"

{helpers}\

{definitions}\
"""

STRUCT_FMT = """\
/**
 * Signals in message {database_message_name}.
 *
{comment}\
 * All signal values are as on the CAN bus.
 */
struct {database_name}_{message_name}_t {{
{members}

    static int unpack(
        struct {database_name}_{message_name}_t *dst_p,
        const uint8_t *src_p,
        size_t size);
    int pack(
        uint8_t *dst_p,
        // const struct {database_name}_{message_name}_t *src_p,
        size_t size);

    {ros_message_name} to_msg();
    static void from_msg(
        struct {database_name}_{message_name}_t *dst_p,
        const {ros_message_name} &src_p);
}};

size_t send_on_can(int fd, const {ros_message_name}& msg);
"""

#  //    struct {database_name}_{message_name}_t *dst_p,
#    * @param[out] dst_p Object to unpack the message into.
DECLARATION_UNPACK_FMT = """\
    /**
     * Unpack message {database_message_name}.
     *
     * @param[in] src_p Message to unpack.
     * @param[in] size Size of src_p.
     *
     * @return zero(0) or negative error code.
     */
    /*
    int {database_name}_{message_name}_t::unpack(
        const uint8_t *src_p,
        size_t size);
    */
"""
DECLARATION_UNPACK_FMT = ""

STRUCT_PROPERTY_FMT = """\
    struct {database_name}_{message_name}_t {database_name}_{message_name};\
"""

# rclcpp::Publisher<sensor_msgs::msg::Imu>::SharedPtr imu_rear_pub;
PUBLISHER_PROPERTY_FMT = """\
    rclcpp::Publisher<vcu_can_msgs_yourcar{season}::msg::{database_name}{message_name}>::SharedPtr {database_name_lower}_{message_name_lower}_pub;\
"""

SIGNAL_DECLARATION_DECODE_FMT = """\
/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
{floating_point_type} {database_name}_{message_name}_{signal_name}_decode({type_name} value);

"""

MESSAGE_DECLARATION_DECODE_FMT = """\
/**
 * Decode given message by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
void {database_name}_{message_name}_decode(struct {database_name}_{message_name}_t *src_p);

"""

SIGNAL_DECLARATION_IS_IN_RANGE_FMT = """\
/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool {database_name}_{message_name}_{signal_name}_is_in_range({type_name} value);
"""

MESSAGE_DECLARATION_INIT_FMT = """\
/**
 * Init message fields to default values from {database_message_name}.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int {database_name}_{message_name}_init(struct {database_name}_{message_name}_t *msg_p);
"""

MESSAGE_DEFINITION_INIT_FMT = """\
int {database_name}_{message_name}_init(struct {database_name}_{message_name}_t *msg_p)
{{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct {database_name}_{message_name}_t));
{init_body}
    return 0;
}}
"""

UNPACK_HELPER_LEFT_SHIFT_FMT = """\
static inline {var_type} unpack_left_shift_u{length}(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{{
    return ({var_type})(({var_type})(value & mask) << shift);
}}
"""

UNPACK_HELPER_RIGHT_SHIFT_FMT = """\
static inline {var_type} unpack_right_shift_u{length}(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{{
    return ({var_type})(({var_type})(value & mask) >> shift);
}}
"""

# //    struct {database_name}_{message_name}_t *dst_p,
DEFINITION_UNPACK_FMT = """\
/*
int {raw_database_name}Data::{database_name}_{message_name}_unpack(
    const uint8_t *src_p,
    size_t size)
{{
{unpack_variables}\
    if (size < {message_length}u) {{
        return (-EINVAL);
    }}
{unpack_body}
    return (0);
}}
*/
"""

SIGNAL_DEFINITION_DECODE_FMT = """\
{floating_point_type} {database_name}_{message_name}_{signal_name}_decode({type_name} value)
{{
    return ({decode});
}}

"""

MESSAGE_DEFINITION_DECODE_FMT = """\
void {database_name}_{message_name}_decode(struct {database_name}_{message_name}_t *src_p)
{{
    {decode_body}
}}

"""

SIGNAL_DEFINITION_IS_IN_RANGE_FMT = """\
bool {database_name}_{message_name}_{signal_name}_is_in_range({type_name} value)
{{
{unused}\
    return ({check});
}}
"""

EMPTY_DEFINITION_FMT = """\
/*
int {raw_database_name}Data::{database_name}_{message_name}_unpack(
    const uint8_t *src_p,
    size_t size)
{{
    (void)src_p;
    (void)size;

    return (0);
}}
*/
"""

SIGN_EXTENSION_FMT = """
    if (({name} & (1{suffix} << {shift})) != 0{suffix}) {{
        {name} |= 0x{mask:x}{suffix};
    }}

"""

SIGNAL_MEMBER_FMT = """\
    /**
{comment}\
     * Range:  {range}
     * Scale:  {scale}
     * Offset: {offset}
     */
    {can_type_name} {name}{length};\

    // {can_type_name} encode_{name}({real_type_name} value);
    // {real_type_name} decode_{name}({can_type_name} value);\
"""

INIT_SIGNAL_BODY_TEMPLATE_FMT = """\
    msg_p->{signal_name} = {signal_initial};
"""


def _strip_blank_lines(lines: List[str]) -> List[str]:
    try:
        while lines[0] == "":
            lines = lines[1:]

        while lines[-1] == "":
            lines = lines[:-1]
    except IndexError:
        pass

    return lines


def _get(value: Optional[_T1], default: _T2) -> Union[_T1, _T2]:
    if value is None:
        return default
    return value


def _format_comment(comment: Optional[str]) -> str:
    if comment:
        return (
            "\n".join(["     * " + line.rstrip() for line in comment.splitlines()])
            + "\n     *\n"
        )
    else:
        return ""


def _format_range(cg_signal: "CodeGenSignal") -> str:
    minimum = cg_signal.signal.minimum
    maximum = cg_signal.signal.maximum

    def phys_to_raw(x: Union[int, float]) -> Union[int, float]:
        raw_val = cg_signal.signal.scaled_to_raw(x)
        if cg_signal.signal.is_float:
            return float(raw_val)
        return round(raw_val)

    if minimum is not None and maximum is not None:
        return (
            f"{phys_to_raw(minimum)}.."
            f"{phys_to_raw(maximum)} "
            f"({round(minimum, 5)}..{round(maximum, 5)} {cg_signal.unit})"
        )
    elif minimum is not None:
        return f"{phys_to_raw(minimum)}.. ({round(minimum, 5)}.. {cg_signal.unit})"
    elif maximum is not None:
        return f"..{phys_to_raw(maximum)} (..{round(maximum, 5)} {cg_signal.unit})"
    else:
        return "-"


def _generate_signal(
    database_name: str,
    cg_message: "CodeGenMessage",
    cg_signal: "CodeGenSignal",
    bit_fields: bool,
) -> str:
    comment = _format_comment(cg_signal.signal.comment)
    range_ = _format_range(cg_signal)
    scale = _get(cg_signal.signal.conversion.scale, "-")
    offset = _get(cg_signal.signal.conversion.offset, "-")

    if cg_signal.signal.conversion.is_float or not bit_fields:
        length = ""
    else:
        length = f" : {cg_signal.signal.length}"

    member = SIGNAL_MEMBER_FMT.format(
        comment=comment,
        database_name=database_name,
        message_name=cg_message.snake_name,
        range=range_,
        scale=scale,
        offset=offset,
        can_type_name=cg_signal.type_name,
        real_type_name=cg_signal.cpp_ros_type_name,
        name=cg_signal.snake_name,
        length=length,
    )

    return member


def _format_unpack_code_signal(
    cg_message: "CodeGenMessage",
    signal_name: str,
    database_name: str,
    body_lines: List[str],
    variable_lines: List[str],
    helper_kinds: Set[THelperKind],
) -> None:
    cg_signal = cg_message.get_signal_by_name(signal_name)
    conversion_type_name = f"uint{cg_signal.type_length}_t"

    if cg_signal.signal.conversion.is_float or cg_signal.signal.is_signed:
        variable = f"    {conversion_type_name} {cg_signal.snake_name} = 0;"
        variable_lines.append(variable)

    segments = cg_signal.segments(invert_shift=True)

    property_access = "this->{0}_{1}.{2}".format(
        database_name, cg_message.hex_snake_name, cg_signal.snake_name
    )

    for i, (index, shift, shift_direction, mask) in enumerate(segments):
        if cg_signal.signal.conversion.is_float or cg_signal.signal.is_signed:
            fmt = "    {} {} unpack_{}_shift_u{}(src_p[{}], {}u, 0x{:02x}u);"
        else:
            fmt = "    {} {} unpack_{}_shift_u{}(src_p[{}], {}u, 0x{:02x}u);"

        line = fmt.format(
            property_access,
            "=" if i == 0 else "|=",
            shift_direction,
            cg_signal.type_length,
            index,
            shift,
            mask,
        )
        body_lines.append(line)
        helper_kinds.add((shift_direction, cg_signal.type_length))

    if cg_signal.signal.conversion.is_float:
        conversion = "    memcpy(&dst_p->{0}, &{0}, sizeof(dst_p->{0}));".format(
            cg_signal.snake_name
        )
        body_lines.append(conversion)
    elif cg_signal.signal.is_signed:
        mask = (1 << (cg_signal.type_length - cg_signal.signal.length)) - 1

        if mask != 0:
            mask <<= cg_signal.signal.length
            formatted = SIGN_EXTENSION_FMT.format(
                name=cg_signal.snake_name,
                shift=cg_signal.signal.length - 1,
                mask=mask,
                suffix=cg_signal.conversion_type_suffix,
            )
            body_lines.extend(formatted.splitlines())

        # this->can4_0x149_gps_rear_velocities.gps_rear_vel_east
        conversion = "    {property_access} = (int{1}_t){0};".format(
            cg_signal.snake_name, cg_signal.type_length, property_access=property_access
        )
        body_lines.append(conversion)


def _format_unpack_code_level(
    cg_message: "CodeGenMessage",
    database_name: str,
    signal_names: Union[List[str], List[Dict[str, Dict[int, List[str]]]]],
    variable_lines: List[str],
    helper_kinds: Set[THelperKind],
) -> List[str]:
    """Format one unpack level in a signal tree."""

    body_lines: List[str] = []
    muxes_lines: List[str] = []

    for signal_name in signal_names:
        if isinstance(signal_name, dict):
            mux_lines = []
            if muxes_lines:
                muxes_lines.append("")

            muxes_lines += mux_lines
        else:
            _format_unpack_code_signal(
                cg_message,
                signal_name,
                database_name,
                body_lines,
                variable_lines,
                helper_kinds,
            )

    if body_lines:
        if body_lines[-1] != "":
            body_lines.append("")

    if muxes_lines:
        muxes_lines.append("")

    body_lines = body_lines + muxes_lines

    if body_lines:
        body_lines = [""] + body_lines

    return body_lines


def _format_unpack_code(
    cg_message: "CodeGenMessage",
    database_name: str,
    helper_kinds: Set[THelperKind],
) -> Tuple[str, str]:
    variable_lines: List[str] = []
    body_lines = _format_unpack_code_level(
        cg_message,
        database_name,
        cg_message.message.signal_tree,
        variable_lines,
        helper_kinds,
    )

    if variable_lines:
        variable_lines = sorted(set(variable_lines)) + ["", ""]

    return "\n".join(variable_lines), "\n".join(body_lines)


def _generate_struct(
    database_name: str, cg_message: "CodeGenMessage", bit_fields: bool
) -> Tuple[str, List[str]]:
    members = []

    for cg_signal in cg_message.cg_signals:
        members.append(
            _generate_signal(database_name.lower(), cg_message, cg_signal, bit_fields)
        )

    if not members:
        members = [""]

    if cg_message.message.comment is None:
        comment = ""
    else:
        comment = f" * {cg_message.message.comment}\n *\n"

    return comment, members


def _format_choices(cg_signal: "CodeGenSignal", signal_name: str) -> List[str]:
    choices = []

    for value, name in sorted(cg_signal.unique_choices.items()):
        if cg_signal.signal.is_signed:
            fmt = "{signal_name}_{name}_CHOICE ({value})"
        else:
            fmt = "{signal_name}_{name}_CHOICE ({value}u)"

        choices.append(
            fmt.format(signal_name=signal_name.upper(), name=str(name), value=value)
        )

    return choices


def _generate_frame_id_defines(
    database_name: str, cg_messages: List["CodeGenMessage"]
) -> str:
    return "\n".join(
        [
            "#define {}_{}_FRAME_ID (0x{:02x}u)".format(
                database_name.upper(),
                cg_message.hex_snake_name.upper(),
                cg_message.message.frame_id,
            )
            for cg_message in cg_messages
        ]
    )


def _generate_frame_length_defines(
    database_name: str, cg_messages: List["CodeGenMessage"]
) -> str:
    result = "\n".join(
        [
            "#define {}_{}_LENGTH ({}u)".format(
                database_name.upper(),
                cg_message.hex_snake_name.upper(),
                cg_message.message.length,
            )
            for cg_message in cg_messages
        ]
    )

    return result


def _generate_frame_cycle_time_defines(
    database_name: str, cg_messages: List["CodeGenMessage"]
) -> str:
    result = "\n".join(
        [
            "#define {}_{}_CYCLE_TIME_MS ({}u)".format(
                database_name.upper(),
                cg_message.hex_snake_name.upper(),
                cg_message.message.cycle_time,
            )
            for cg_message in cg_messages
            if cg_message.message.cycle_time is not None
        ]
    )

    return result


def _generate_is_extended_frame_defines(
    database_name: str, cg_messages: List["CodeGenMessage"]
) -> str:
    result = "\n".join(
        [
            "#define {}_{}_IS_EXTENDED ({})".format(
                database_name.upper(),
                cg_message.hex_snake_name.upper(),
                int(cg_message.message.is_extended_frame),
            )
            for cg_message in cg_messages
        ]
    )

    return result


def _generate_choices_defines(
    database_name: str,
    cg_messages: List["CodeGenMessage"],
) -> str:
    choices_defines = []

    for cg_message in cg_messages:
        for cg_signal in cg_message.cg_signals:
            if cg_signal.signal.conversion.choices is None:
                continue

            choices = _format_choices(cg_signal, cg_signal.snake_name)
            signal_choices_defines = "\n".join(
                [
                    f"#define {database_name.upper()}_{cg_message.hex_snake_name.upper()}_{choice}"
                    for choice in choices
                ]
            )
            choices_defines.append(signal_choices_defines)

    return "\n\n".join(choices_defines)


def _generate_frame_name_macros(
    database_name: str,
    cg_messages: List["CodeGenMessage"],
) -> str:
    result = "\n".join(
        [
            '#define {}_{}_NAME "{}"'.format(
                database_name.upper(),
                cg_message.hex_snake_name.upper(),
                cg_message.message.name,
            )
            for cg_message in cg_messages
        ]
    )

    return result


def _generate_signal_name_macros(
    database_name: str,
    cg_messages: List["CodeGenMessage"],
) -> str:
    result = "\n".join(
        [
            '#define {}_{}_{}_NAME "{}"'.format(
                database_name.upper(),
                cg_message.hex_snake_name.upper(),
                cg_signal.snake_name.upper(),
                cg_signal.signal.name,
            )
            for cg_message in cg_messages
            for cg_signal in cg_message.cg_signals
        ]
    )

    return result


def _generate_structs(
    database_name: str,
    cg_messages: List["CodeGenMessage"],
    bit_fields: bool,
) -> str:
    structs = []

    for cg_message in cg_messages:
        comment, members = _generate_struct(database_name, cg_message, bit_fields)

        ros_message_name = database_name + cg_message.pascal_name
        ros_message_name = f"vcu_can_msgs_yourcar{season}::msg::{ros_message_name}"

        structs.append(
            STRUCT_FMT.format(
                comment=comment,
                database_message_name=cg_message.message.name,
                message_name=cg_message.hex_snake_name,
                ros_message_name=ros_message_name,
                database_name=database_name.lower(),
                members="\n\n".join(members),
            )
        )

    return "\n".join(structs)


def _generate_property_declarations(
    database_name: str, cg_messages: List["CodeGenMessage"]
) -> str:
    declarations = []

    for cg_message in cg_messages:
        declaration = ""

        declaration += STRUCT_PROPERTY_FMT.format(
            database_name=database_name.lower(), message_name=cg_message.hex_snake_name
        )
        declaration += "\n"
        declaration += PUBLISHER_PROPERTY_FMT.format(
            database_name=database_name,
            message_name=cg_message.pascal_name,
            database_name_lower=database_name.lower(),
            message_name_lower=cg_message.hex_snake_name,
            season=season,
        )
        declaration += "\n"

        if declaration:
            declarations.append(declaration)

    return "\n".join(declarations)


def _generate_declarations(
    database_name: str, cg_messages: List["CodeGenMessage"]
) -> str:
    declarations = []

    for cg_message in cg_messages:
        signal_declarations = []

        declaration = ""

        declaration += DECLARATION_UNPACK_FMT.format(
            database_name=database_name.lower(),
            database_message_name=cg_message.message.name,
            message_name=cg_message.hex_snake_name,
        )

        if signal_declarations:
            declaration += "\n" + "\n".join(signal_declarations)

        if declaration:
            declarations.append(declaration)

    return "\n".join(declarations)


def _generate_definitions(
    database_name: str, cg_messages: List["CodeGenMessage"], use_float: bool
) -> Tuple[str, Tuple[Set[THelperKind], Set[THelperKind]]]:
    definitions = []
    pack_helper_kinds: Set[THelperKind] = set()
    unpack_helper_kinds: Set[THelperKind] = set()

    for cg_message in cg_messages:
        signal_definitions = []
        signals_init_body = ""

        for cg_signal in cg_message.cg_signals:
            if use_float and cg_signal.type_name == "double":
                warnings.warn(
                    f"User selected `--use-float`, but database contains "
                    f"signal with data type `double`: "
                    f'"{cg_message.message.name}::{cg_signal.signal.name}"',
                    stacklevel=2,
                )
                _use_float = False
            else:
                _use_float = use_float

            if cg_signal.signal.initial:
                signals_init_body += INIT_SIGNAL_BODY_TEMPLATE_FMT.format(
                    signal_initial=cg_signal.signal.raw_initial,
                    signal_name=cg_signal.snake_name,
                )

        definition = ""

        if cg_message.message.length > 0:
            unpack_variables, unpack_body = _format_unpack_code(
                cg_message, database_name.lower(), unpack_helper_kinds
            )

            definition += DEFINITION_UNPACK_FMT.format(
                raw_database_name=database_name,
                database_name=database_name.lower(),
                database_message_name=cg_message.message.name,
                message_name=cg_message.hex_snake_name,
                message_length=cg_message.message.length,
                unpack_variables=unpack_variables,
                unpack_body=unpack_body,
            )

        if cg_message.message.length == 0 or len(cg_message.cg_signals) == 0:
            definition = EMPTY_DEFINITION_FMT.format(
                raw_database_name=database_name,
                database_name=database_name.lower(),
                message_name=cg_message.hex_snake_name,
            )

        if signal_definitions:
            definition += "\n" + "\n".join(signal_definitions)

        if definition:
            definitions.append(definition)

    return "\n".join(definitions), (pack_helper_kinds, unpack_helper_kinds)


def _generate_helpers_kind(
    kinds: Set[THelperKind], left_format: str, right_format: str
) -> List[str]:
    formats = {"left": left_format, "right": right_format}
    helpers = []

    for shift_direction, length in sorted(kinds):
        var_type = f"uint{length}_t"
        helper = formats[shift_direction].format(length=length, var_type=var_type)
        helpers.append(helper)

    return helpers


def _generate_helpers(kinds: Tuple[Set[THelperKind], Set[THelperKind]]) -> str:
    unpack_helpers = _generate_helpers_kind(
        kinds[1], UNPACK_HELPER_LEFT_SHIFT_FMT, UNPACK_HELPER_RIGHT_SHIFT_FMT
    )
    helpers = unpack_helpers

    if helpers:
        helpers.append("")

    return "\n".join(helpers)


def gen_c_unpacking(
    database: "Database",
    database_name: str,
    header_name: str,
    commit_hash: str,
    bit_fields: bool = False,
    use_float: bool = False,
) -> tuple[str, str]:
    """Generate C source code from given CAN database `database`.

    `database_name` is used as a prefix for all defines, data
    structures and functions.

    `header_name` is the file name of the C header file, which is
    included by the C source file.

    Set `bit_fields` to ``True`` to generate bit fields in structs.

    Set `use_float` to ``True`` to prefer the `float` type instead
    of the `double` type for floating point numbers.

    This function returns a tuple of the C header and source files as
    strings.

    """
    database_name_lower = database_name.lower()

    # date = time.ctime()
    date = commit_hash

    cg_messages = [CodeGenMessage(message) for message in database.messages]
    include_guard = f"{database_name.upper()}_H"
    frame_id_defines = _generate_frame_id_defines(database_name_lower, cg_messages)
    frame_length_defines = _generate_frame_length_defines(
        database_name_lower, cg_messages
    )
    is_extended_frame_defines = _generate_is_extended_frame_defines(
        database_name_lower, cg_messages
    )
    frame_cycle_time_defines = _generate_frame_cycle_time_defines(
        database_name_lower, cg_messages
    )
    choices_defines = _generate_choices_defines(database_name_lower, cg_messages)

    frame_name_macros = _generate_frame_name_macros(database_name_lower, cg_messages)
    signal_name_macros = _generate_signal_name_macros(database_name_lower, cg_messages)

    structs = _generate_structs(database_name, cg_messages, bit_fields)
    function_declarations = _generate_declarations(database_name, cg_messages)
    variable_declarations = _generate_property_declarations(database_name, cg_messages)

    definitions, helper_kinds = _generate_definitions(
        database_name, cg_messages, use_float
    )
    helpers = _generate_helpers(helper_kinds)

    includes = ""
    for msg in cg_messages:
        includes += f'#include "vcu_can_msgs_yourcar{season}/msg/{database_name.lower()}_{msg.snake_name}.hpp"\n'

    header = HEADER_FMT.format(
        version=__version__,
        date=date,
        include_guard=include_guard,
        includes=includes,
        raw_database_name=database_name,
        lower_database_name=database_name.lower(),
        frame_id_defines=frame_id_defines,
        frame_length_defines=frame_length_defines,
        is_extended_frame_defines=is_extended_frame_defines,
        frame_cycle_time_defines=frame_cycle_time_defines,
        choices_defines=choices_defines,
        frame_name_macros=frame_name_macros,
        signal_name_macros=signal_name_macros,
        structs=structs,
        function_declarations=function_declarations,
        variable_declarations=variable_declarations,
    )

    source = SOURCE_FMT.format(
        version=__version__,
        date=date,
        header=header_name,
        helpers=helpers,
        definitions=definitions,
    )

    return header, source
