std_msgs/Header header

float32 apps1                       # Acceleration Pedal Position Sensor 1
float32 apps2                       # Acceleration Pedal Position Sensor 2
float32 brakeforce                  # Recu pedal sensor
float32 brake_pressure_front        # Brake Pressure of the front brake cycle
float32 brake_pressure_rear         # Brake Pressure of the rear brake cycle
float32 ebs_pressure_front          # EBS Pressure of the 1. EBS reservoir
float32 ebs_pressure_rear           # EBS Pressure of the 2. EBS reservoir
float32 steering_angle              # Steering Angle in degree
float32 apps1_pressed               # Config value for pressed APPs 1
float32 apps1_released              # Config value for released APPs 1
float32 apps2_pressed               # Config value for pressed APPs2
float32 apps2_released              # Config value for released APPs2