# Messages that is sended to the mailman from the VCU node to control the Power Distribution Unit

std_msgs/Header header

bool power_lidar_swr
bool power_inverter
bool power_rtds
bool power_brakelight
bool vehicle_mode
uint8 vehicle_control_mode
bool power_sdc
bool power_ods
bool power_res_racing_mode
bool power_ssb
bool power_can_logger
bool power_lidar_swl
bool power_lidar_mh
bool power_tire_temp
bool power_res
bool power_lv_steering_actuator
bool power_assi
bool power_fan_swl
bool power_ogss
bool power_ogss_schenkler
bool power_fan_swr
bool power_lv_dcdc_12
bool power_lv_dcdc_pc
bool power_lv_dcdc_akku
bool power_driver_communication
bool enable_push_to_talk

float32 pwm_cooling_pump
float32 pwm_ebs_pump
float32 pwm_accu_fan
float32 pwm_pg_right
float32 pwm_pg_left
float32 pwm_swl_fan
float32 pwm_swr_fan 

bool power_lv_dcdc_12_2
bool ethernet
