builtin_interfaces/Time stamp

# Radiator Temps
float32 temp_rad_swl_in
float32 temp_rad_swl_out
float32 temp_rad_swr_in
float32 temp_rad_swr_out

# Temps from the Inverter
# Unit: °C
float32 actual_temp_motor1
float32 actual_temp_motor2
float32 actual_temp_motor3
float32 actual_temp_motor4

# Actual temperature of power switches
# Unit: °C
float32 actual_temp_pwr_module1
float32 actual_temp_pwr_module2
float32 actual_temp_pwr_module3
float32 actual_temp_pwr_module4

# Actual temperature for additonal sensor channel 0 and 5
# Unit: °C
float32 actual_temp_add_sensor0
float32 actual_temp_add_sensor5

# Actual temperature of the carrier board
# Unit: °C
float32 actual_temp_carrier